export const constants = {
    CHECK_AUTH: 'CHECK_AUTH',
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    VERIFY_MAIL: 'VERIFY_MAIL',
    LOG_OUT: 'LOG_OUT',
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILED: 'AUTH_FAILED',
    AUTH_ERROR: 'AUTH_ERROR',
    RESET_AUTH_MESSAGES: 'RESET_AUTH_MESSAGES'
}