export const constants = {
    GET_NEW_NOTIFICATIONS_QTY: 'GET_NEW_NOTIFICATIONS_QTY',
    SET_NEW_NOTIFICATIONS_QTY: 'SET_NEW_NOTIFICATIONS_QTY',
    GET_NOTIFICATIONS_LIST: 'GET_NOTIFICATIONS_LIST',
    GET_NOTIFICATIONS_LIST_START: 'GET_NOTIFICATIONS_LIST_START',
    GET_NOTIFICATIONS_LIST_SUCCESS: 'GET_NOTIFICATIONS_LIST_SUCCESS',
    RESET_NOTIFICATIONS: 'RESET_NOTIFICATIONS'
}