export const constants = {
    SEARCH_USERS: 'SEARCH_USERS',
    SEARCH_USERS_START: 'SEARCH_USERS_START',
    SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
    GET_USER_INFO: 'GET_USER_INFO',
    GET_USER_INFO_START: 'GET_USER_INFO_START',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    UPLOAD_AVATAR: 'UPLOAD_AVATAR',
    UPLOAD_AVATAR_START: 'UPLOAD_AVATAR_START',
    UPLOAD_AVATAR_SUCCESS: 'UPLOAD_AVATAR_SUCCESS',
    SET_IS_FRIEND: 'SET_IS_FRIEND',
    SET_IS_SENT_FRIEND_REQUEST: 'SET_IS_SET_FRIEND_REQUEST',
    SET_IS_SENDING_FRIEND_REQUEST: 'SET_IS_SENDING_FRIEND_REQUEST',
    RESET_SEARCHED_USERS: 'RESET_SEARCHED_USERS',
    RESET_CURRENT_USER: 'RESET_CURRENT_USER'
}